version: "v3.0"
name: My first pipeline
semaphore_image: standard
blocks:
  - name: "Stage 1"
    build:
      prologue:
        commands:
          - checkout && cd $SEMAPHORE_GIT_DIR
      epilogue:
        commands:
          - echo "Yay job finished"
          - echo $SEMAPHORE_JOB_RESULT
      env_vars:
        - name: SEMAPHORE_CACHE_USERNAME
          value: "u180539"
        - name: SEMAPHORE_CACHE_URL
          value: "u180539.your-storagebox.de"

      jobs:
      - name: Install bundle
        commands:
          - pwd
          - wget https://raw.githubusercontent.com/semaphoreci/toolbox/master/cache && chmod +x cache
          - ./cache restore --key Gemfile.lock
          - bundle install --path=vendor/bundle
          - ./cache store --key Gemfile.lock --path vendor

      - name: List files
        commands:
          - ls -l vendor

  - name: "Stage 2"
    build:
      jobs:
      - name: Echo job
        commands:
          - checkout
          - cd $SEMAPHORE_GIT_DIR
          - pwd
          - echo $SEMAPHORE_PIPELINE_ID
          - echo "Hello from $SEMAPHORE_JOB_ID"
